### ISSUE TITLE
Create KOReader plugin for toggling on/off

### ISSUE THREAD

**Issue by nikosavola** [sublipri/kobo-wifi-remote#3]
Hi, thanks for the great work!

I wonder would it be possible to add a KOReader plugin that adds a menu item for the HTTP server toggle, effectively doing the same as the NickelMenu one. I never exit KOReader on my Kobo :)

I could also look into this if I find time for it.

Some example plugins may be seen at https://github.com/koreader/contrib

**Comment by sublipri** [comment]
Hi!

I had a quick try at doing this based on [this example](https://github.com/koreader/koreader/tree/master/plugins/hello.koplugin). You'll need to manually install it from [here](https://github.com/sublipri/kobo-wifi-remote/tree/koreader-plugin) to test. It should appear at the bottom of the tools menu. Let me know if it works for you or if there's anything you think should be different. :)

**Comment by sublipri** [comment]
I'm going to merge the PR in preparation for a new release.  Feel free to open a new issue if you think it could be improved. I'm not very familiar with KOReader so it's possible there's a better way to do it I'm not aware of.
